export const defaultAsrProvider = {
  label: "阿里云百炼 Fun-ASR（中文/多语言）",
  transport: "dashscope-funasr",
  model: "fun-asr",
  functionId: "",
  endpoint: "https://dashscope.aliyuncs.com/api/v1",
  languageCode: "zh",
  sendModel: false,
  videoInputMode: "original",
  apiKey: "",
  lastTest: null,
};

export const asrProviderPresets = [
  {
    label: "阿里云百炼 Fun-ASR（中文/多语言）",
    transport: "dashscope-funasr",
    model: "fun-asr",
    functionId: "",
    endpoint: "https://dashscope.aliyuncs.com/api/v1",
    languageCode: "zh",
    sendModel: false,
    videoInputMode: "original",
  },
  {
    label: "阿里云百炼 Qwen3-ASR 文件转写",
    transport: "dashscope-funasr",
    model: "qwen3-asr-flash-filetrans",
    functionId: "",
    endpoint: "https://dashscope.aliyuncs.com/api/v1",
    languageCode: "zh",
    sendModel: false,
    videoInputMode: "original",
  },
  {
    label: "OpenAI Whisper API",
    transport: "nvidia-http",
    model: "whisper-1",
    functionId: "",
    endpoint: "https://api.openai.com/v1/audio/transcriptions",
    languageCode: "multi",
    sendModel: true,
    videoInputMode: "extract",
  },
  {
    label: "Groq Whisper（OpenAI Compatible）",
    transport: "nvidia-http",
    model: "whisper-large-v3-turbo",
    functionId: "",
    endpoint: "https://api.groq.com/openai/v1/audio/transcriptions",
    languageCode: "multi",
    sendModel: true,
    videoInputMode: "extract",
  },
  {
    label: "NVIDIA NIM HTTP（自部署/远程）",
    transport: "nvidia-http",
    model: "",
    functionId: "",
    endpoint: "",
    languageCode: "multi",
    sendModel: false,
    videoInputMode: "extract",
  },
  {
    label: "自定义 HTTP 转写端点",
    transport: "nvidia-http",
    model: "",
    functionId: "",
    endpoint: "",
    languageCode: "multi",
    sendModel: true,
    videoInputMode: "extract",
  },
  {
    label: "自定义 NVIDIA Riva gRPC",
    transport: "nvidia-riva-grpc",
    model: "",
    functionId: "",
    endpoint: "grpc.nvcf.nvidia.com:443",
    languageCode: "multi",
    videoInputMode: "extract",
  },
];
